### PR TITLE
Fixes #32454 - Show new msg for empty update commands

### PR DESCRIPTION
**Pull request by ofedoren**
requires https://github.com/theforeman/hammer-cli/pull/343

Most of the update commands follow API docs and put resource related params under `resource` key in `request_params`. Thanks to this, we can simply check if anything is being put there and show `Nothing to update` message if not.

### CODE REVIEW

**Review by yifatmakias — CHANGES_REQUESTED** [review]
Thanks @ofedoren, but it seems that there is some issues with the tests after your changes.
Can you take a look?

**Comment by ofedoren** [comment]
@yifatmakias, rebased. All the related tests are green now :)

There are 2 tests that are currently failing, but they are related to changes in https://github.com/theforeman/hammer-cli/pull/345.

I can try to fix them within this PR, but I guess it's better to create another one for that purpose.

**Review by yifatmakias — APPROVED** [review]
@ofedoren Thanks, looks good to me.

**Comment by adiabramovitch** [comment]
@ofedoren when i am trying to use the update command I get this msg, is it just me?
Could not update the host:
  Error: undefined method `resource' for nil:NilClass
  Did you mean?  rescue
